using System.Diagnostics; using System.Net; using System.Net.Http; using System.Security.Cryptography; using System.Text; using System.Text.Json;
namespace CodexAccountBar.Services;
public sealed class CodexService
{
    public string CodexHome=>Environment.GetEnvironmentVariable("CODEX_HOME") is{Length:>0}v?v:Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.UserProfile),".codex"); public string AuthPath=>Path.Combine(CodexHome,"auth.json");
    public async Task<string?> ReadActiveAuthAsync()=>File.Exists(AuthPath)?await File.ReadAllTextAsync(AuthPath):null;
    public async Task RestoreOfficialConfigAsync()
    {
        var path=Path.Combine(CodexHome,"config.toml");if(!File.Exists(path))return;var lines=await File.ReadAllLinesAsync(path);var output=new List<string>();var section=new List<string>();
        void Flush(){if(section.Count==0)return;var block=string.Join("\n",section);if(!block.Contains("9router",StringComparison.OrdinalIgnoreCase)&&!block.Contains("localhost:20128",StringComparison.OrdinalIgnoreCase)&&!block.Contains("127.0.0.1:20128",StringComparison.OrdinalIgnoreCase))output.AddRange(section);section.Clear();}
        foreach(var line in lines){var trimmed=line.Trim();if(trimmed.StartsWith('[')){Flush();section.Add(line);continue;}if(section.Count>0){section.Add(line);continue;}if(trimmed.StartsWith("model_provider",StringComparison.OrdinalIgnoreCase)&&(trimmed.Contains("9router",StringComparison.OrdinalIgnoreCase)||trimmed.Contains("router",StringComparison.OrdinalIgnoreCase)))continue;if((trimmed.StartsWith("base_url",StringComparison.OrdinalIgnoreCase)||trimmed.StartsWith("api_base",StringComparison.OrdinalIgnoreCase))&&(trimmed.Contains(":20128",StringComparison.OrdinalIgnoreCase)||trimmed.Contains("9router",StringComparison.OrdinalIgnoreCase)))continue;output.Add(line);}Flush();var updated=string.Join(Environment.NewLine,output).TrimEnd()+Environment.NewLine;if(updated!=string.Join(Environment.NewLine,lines).TrimEnd()+Environment.NewLine){var backup=path+".codex-bar.bak";File.Copy(path,backup,true);await File.WriteAllTextAsync(path+".tmp",updated);File.Move(path+".tmp",path,true);}
    }
    public async Task WriteAndRestartAsync(string json){Directory.CreateDirectory(CodexHome);using(JsonDocument.Parse(json)){}var temp=AuthPath+".cab.tmp";await File.WriteAllTextAsync(temp,json);File.Move(temp,AuthPath,true);await Restart();}
    public async Task<string> LoginIsolatedAsync()
    {
        const string clientId="app_EMoamEEZ73f0CkXaXp7hrann";var verifier=Base64Url(RandomNumberGenerator.GetBytes(32));var challenge=Base64Url(SHA256.HashData(Encoding.ASCII.GetBytes(verifier)));var state=Base64Url(RandomNumberGenerator.GetBytes(32));
        HttpListener? listener=null;int port=1455;foreach(var candidate in new[]{1455,1457}){try{listener=new HttpListener();listener.Prefixes.Add($"http://localhost:{candidate}/");listener.Start();port=candidate;break;}catch{listener?.Close();listener=null;}}if(listener is null)throw new InvalidOperationException("Could not start the local login callback. Try closing another Codex login window and retry.");
        using(listener){var redirect=$"http://localhost:{port}/auth/callback";var query=string.Join("&",new Dictionary<string,string>{{"response_type","code"},{"client_id",clientId},{"redirect_uri",redirect},{"scope","openid profile email offline_access api.connectors.read api.connectors.invoke"},{"code_challenge",challenge},{"code_challenge_method","S256"},{"id_token_add_organizations","true"},{"codex_cli_simplified_flow","true"},{"state",state},{"originator","codex_cli_rs"}}.Select(x=>$"{Uri.EscapeDataString(x.Key)}={Uri.EscapeDataString(x.Value)}"));Process.Start(new ProcessStartInfo($"https://auth.openai.com/oauth/authorize?{query}"){UseShellExecute=true});using var timeout=new CancellationTokenSource(TimeSpan.FromMinutes(10));HttpListenerContext context;try{context=await listener.GetContextAsync().WaitAsync(timeout.Token);}catch(TimeoutException){throw new TimeoutException("Login timed out or was cancelled.");}var code=context.Request.QueryString["code"];var returnedState=context.Request.QueryString["state"];var error=context.Request.QueryString["error"];var response=Encoding.UTF8.GetBytes(error is null?"<html><body>Sign-in complete. You may close this tab.</body></html>":"<html><body>Sign-in was cancelled. You may close this tab.</body></html>");context.Response.ContentType="text/html";context.Response.ContentLength64=response.Length;await context.Response.OutputStream.WriteAsync(response);context.Response.Close();if(error is not null)throw new InvalidOperationException("Codex sign-in was cancelled.");if(code is null||returnedState!=state)throw new InvalidOperationException("Codex sign-in callback was invalid.");using var http=new HttpClient();using var form=new FormUrlEncodedContent(new Dictionary<string,string>{{"grant_type","authorization_code"},{"code",code},{"redirect_uri",redirect},{"client_id",clientId},{"code_verifier",verifier}});using var tokenResponse=await http.PostAsync("https://auth.openai.com/oauth/token",form);var tokenJson=await tokenResponse.Content.ReadAsStringAsync();if(!tokenResponse.IsSuccessStatusCode)throw new InvalidOperationException("Codex sign-in token exchange failed.");using var tokenDoc=JsonDocument.Parse(tokenJson);var tokens=tokenDoc.RootElement;var auth=new{auth_mode="chatgpt",OPENAI_API_KEY=(string?)null,tokens=new{id_token=tokens.GetProperty("id_token").GetString(),access_token=tokens.GetProperty("access_token").GetString(),refresh_token=tokens.GetProperty("refresh_token").GetString(),account_id=(string?)null},last_refresh=DateTimeOffset.UtcNow};return JsonSerializer.Serialize(auth);}
    }
    private static string Base64Url(byte[] bytes)=>Convert.ToBase64String(bytes).TrimEnd('=').Replace('+','-').Replace('/','_');
    private static async Task Restart()
    {
        var current=Environment.ProcessId;var apps=Process.GetProcesses().Where(p=>p.Id!=current).Select(p=>{try{return (p,p.MainModule?.FileName);}catch{return (p,null);}}).Where(x=>x.Item2 is not null&&x.Item2.Contains("\\WindowsApps\\OpenAI.Codex_",StringComparison.OrdinalIgnoreCase)).ToList();
        foreach(var (p,_) in apps){try{p.Kill(true);await p.WaitForExitAsync();}catch{}finally{p.Dispose();}}
        try{Process.Start(new ProcessStartInfo("explorer.exe"){UseShellExecute=true,ArgumentList={"shell:AppsFolder\\OpenAI.Codex_2p2nqsd0c76g0!App"}});}catch{}
    }
}
